// The page's interface languages. English lives at the site root, the others
// at /pl/, /de/ and /it/ (pages generated by scripts/build-langs.js). Each
// i18n-xx.js file registers one language: interface strings, story captions,
// group and region names, false-friend meanings and the How it works panel.
// The language picked also sets the source language of typed words.
(function (root) {
  "use strict";

  const UI_LANGS = ["en", "pl", "de", "it"];
  const STRINGS = {};

  function add(lang, strings) {
    STRINGS[lang] = strings;
  }

  // From ?lang=xx, else from a /xx/ path segment (/word-map/pl/, .../pl/index.html).
  function detectLang(loc) {
    const fromQuery = new URLSearchParams(loc.search || "").get("lang");
    if (UI_LANGS.includes(fromQuery)) return fromQuery;
    const m = (loc.pathname || "").match(/\/([a-z]{2})\/(?:index\.html)?$/);
    return m && UI_LANGS.includes(m[1]) ? m[1] : "en";
  }

  // Where each interface language lives, relative to the site root.
  function langPath(lang, isFile) {
    const page = isFile ? "index.html" : "";
    return lang === "en" ? page || "./" : `${lang}/${page}`;
  }

  // A string from the interface, with {name} placeholders filled in. Falls
  // back to English, then to the key, so a missing string is visible, not blank.
  function t(lang, key, vars) {
    const s = (STRINGS[lang] && STRINGS[lang].ui[key]) ?? STRINGS.en?.ui[key] ?? key;
    return typeof s === "string" ? s.replace(/\{(\w+)\}/g, (_, k) => (vars && k in vars ? vars[k] : `{${k}}`)) : s;
  }

  // Interface-language names for languages and countries, from the browser, as
  // they are written mid-sentence ("polacco" in Italian, "Polnisch" in German).
  function displayName(lang, code, type) {
    try {
      return new Intl.DisplayNames([lang], { type, fallback: "code" }).of(code) || code;
    } catch {
      return code;
    }
  }

  // The same at the start of a line.
  const capitalise = (lang, s) => s.charAt(0).toLocaleUpperCase(lang) + s.slice(1);

  const api = { UI_LANGS, STRINGS, add, detectLang, langPath, t, displayName, capitalise };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.EuropeI18n = api;
})(typeof window !== "undefined" ? window : globalThis);
