// Words with a story across Europe's language families: Latin, Germanic,
// Slavic, and the ones that crossed between them. Same format as presets.js
// (word, or [word, romanisation]); `note` is shown under the buttons when the
// word is on the map, with a button to compare against `ref`, the language
// whose view tells the story best. `groups` (optional) are named groups by
// origin, shown instead of the automatic sound clusters when no country is selected. Loaded after presets.js, which it extends.
(function (root) {
  "use strict";

  const STORIES = {
    Thursday: {
      // Grouped by the origin of the word, which sound alone cannot recover here.
      groups: [
        ["Thor's day", "en de nl lb da no sv fo fi"],
        ["Jupiter's day", "fr it es ca gl ro cy"],
        ["the fourth day", "pl cs sk ru uk be bg sr hr bs mk sl hu lv lt et"],
        ["the fifth day", "pt el tr hy ka is mt"],
      ],
      ref: "fr",
      note: "Latin countries named it after Jupiter (jeudi, giovedì, jueves), Germanic ones after Thor (Thursday, Donnerstag, torsdag). Slavs simply count: the fourth day (czwartek, четверг, čtvrtek), and Hungarian csütörtök is borrowed from them. Portuguese quinta-feira and Greek Πέμπτη count too: the fifth day, counting from Sunday.",
      words: {
        sq: ["e enjte", "enjte"], hy: ["հինգշաբթի", "hingshabti"], az: "cümə axşamı",
        eu: "osteguna", be: ["чацвер", "chatsver"], bs: "četvrtak",
        bg: ["четвъртък", "chetvartak"], ca: "dijous", hr: "četvrtak", cs: "čtvrtek",
        da: "torsdag", nl: "donderdag", en: "Thursday", et: "neljapäev", fo: "hósdagur",
        fi: "torstai", fr: "jeudi", gl: ["xoves", "shoves"], ka: ["ხუთშაბათი", "khutshabati"],
        de: "Donnerstag", el: ["Πέμπτη", "pempti"], hu: ["csütörtök", "chütörtök"], is: "fimmtudagur",
        ga: "Déardaoin", it: ["giovedì", "jovedi"], lv: "ceturtdiena", lt: "ketvirtadienis",
        lb: "Donneschdeg", mk: ["четврток", "chetvrtok"], mt: ["il-Ħamis", "Hamis"],
        no: "torsdag", pl: "czwartek", pt: "quinta-feira", ro: "joi",
        ru: ["четверг", "chetverg"], sr: ["четвртак", "četvrtak"], sk: "štvrtok",
        sl: "četrtek", es: "jueves", sv: "torsdag", tr: "perşembe",
        uk: ["четвер", "chetver"], cy: ["dydd Iau", "Iau"],
      },
    },
    Saturday: {
      // Grouped by the origin of the word, which sound alone cannot recover here.
      groups: [
        ["Sabbath", "pl cs sk ru uk be bg sr hr bs mk sl hu it es pt gl ca fr ro de lb el hy ka mt az"],
        ["Saturn's day", "en nl ga cy sq"],
        ["washing day", "sv da no is fo fi et"],
        ["the sixth day", "lv lt"],
      ],
      ref: "pl",
      note: "Most of Europe kept the Hebrew Sabbath: sobota, суббота, sábado, sabato, samedi, Samstag, szombat. English Saturday and Dutch zaterdag kept the Roman god Saturn. Swedish lördag and Finnish lauantai mean 'washing day'.",
      words: {
        sq: ["e shtunë", "shtunë"], hy: ["շաբաթ", "shabat"], az: "şənbə", eu: "larunbata",
        be: ["субота", "subota"], bs: "subota", bg: ["събота", "sabota"], ca: "dissabte",
        hr: "subota", cs: "sobota", da: "lørdag", nl: "zaterdag", en: "Saturday",
        et: "laupäev", fo: "leygardagur", fi: "lauantai", fr: "samedi", gl: "sábado",
        ka: ["შაბათი", "shabati"], de: "Samstag", el: ["Σάββατο", "savato"], hu: ["szombat", "sombat"],
        is: "laugardagur", ga: ["Dé Sathairn", "Sathairn"], it: "sabato", lv: "sestdiena",
        lt: "šeštadienis", lb: "Samschdeg", mk: ["сабота", "sabota"], mt: ["is-Sibt", "Sibt"],
        no: "lørdag", pl: "sobota", pt: "sábado", ro: "sâmbătă", ru: ["суббота", "subbota"],
        sr: ["субота", "subota"], sk: "sobota", sl: "sobota", es: "sábado", sv: "lördag",
        tr: "cumartesi", uk: ["субота", "subota"], cy: ["dydd Sadwrn", "Sadwrn"],
      },
    },
    Christmas: {
      // Grouped by the origin of the word, which sound alone cannot recover here.
      groups: [
        ["birth (Latin natalis)", "fr it es pt ca gl cy ga tr"],
        ["birth (Slavic)", "pl ru uk"],
        ["Božić, 'little god'", "hr bs sr sl mk"],
        ["Yule", "sv da no is fo fi et"],
        ["Roman calendae", "lt bg be"],
        ["from Weihnachten", "de cs sk"],
        ["Christ's …", "en nl lb sq el"],
        ["kračun", "ro hu"],
      ],
      ref: "it",
      note: "Latin and Celtic countries say 'birth' (Noël, Natale, Navidad, Nadolig, Nollaig), and so do Poles and Russians (Boże Narodzenie, Рождество). The North kept the pagan Yule (jul, joulu, jól). Czech Vánoce and Slovak Vianoce come from German Weihnachten; Lithuanian Kalėdos, Bulgarian Коледа and Belarusian Каляды from the Roman calendae.",
      words: {
        sq: "Krishtlindje", hy: ["Սուրբ Ծնունդ", "Surb Tsnund"], az: "Milad bayramı",
        eu: "Eguberri", be: ["Каляды", "Kaliady"], bs: "Božić", bg: ["Коледа", "Koleda"],
        ca: "Nadal", hr: "Božić", cs: "Vánoce", da: "jul", nl: "Kerstmis", en: "Christmas",
        et: "jõulud", fo: "jól", fi: "joulu", fr: "Noël", gl: "Nadal",
        ka: ["შობა", "shoba"], de: "Weihnachten", el: ["Χριστούγεννα", "hristugena"],
        hu: ["karácsony", "karachoni"], is: "jól", ga: "Nollaig", it: "Natale", lv: "Ziemassvētki",
        lt: "Kalėdos", lb: "Chrëschtdag", mk: ["Божиќ", "Božikj"], mt: ["il-Milied", "Milied"],
        no: "jul", pl: "Boże Narodzenie", pt: "Natal", ro: "Crăciun",
        ru: ["Рождество", "Rozhdestvo"], sr: ["Божић", "Božić"], sk: "Vianoce",
        sl: "božič", es: "Navidad", sv: "jul", tr: "Noel", uk: ["Різдво", "Rizdvo"],
        cy: "Nadolig",
      },
    },
    king: {
      ref: "pl",
      note: "The Slavic word (król, король, kralj) comes from Karl: Charlemagne. Hungarians, Lithuanians, Latvians and Turks then took it from the Slavs (király, karalius, karalis, kral). Finns and Estonians borrowed the Germanic word (kuningas). Latin countries kept rex: roi, re, rey, rege.",
      words: {
        sq: "mbret", hy: ["թագավոր", "tagavor"], az: "kral", eu: "errege",
        be: ["кароль", "karol"], bs: "kralj", bg: ["крал", "kral"], ca: "rei", hr: "kralj",
        cs: "král", da: "konge", nl: "koning", en: "king", et: "kuningas", fo: "kongur",
        fi: "kuningas", fr: "roi", gl: "rei", ka: ["მეფე", "mepe"], de: "König",
        el: ["βασιλιάς", "vasilias"], hu: "király", is: "konungur", ga: "rí", it: "re",
        lv: "karalis", lt: "karalius", lb: "Kinnek", mk: ["крал", "kral"], mt: "re",
        no: "konge", pl: "król", pt: "rei", ro: "rege", ru: ["король", "korol"],
        sr: ["краљ", "kralj"], sk: "kráľ", sl: "kralj", es: "rey", sv: "kung", tr: "kral",
        uk: ["король", "korol"], cy: "brenin",
      },
    },
    bread: {
      ref: "pl",
      note: "Slavic chleb and хлеб, and Finnish leipä, were borrowed from Gothic hlaifs, the same word as English 'loaf'. Latin countries kept panis: pain, pane, pan, pâine. Croats and Slovenes say kruh.",
      words: {
        sq: "bukë", hy: ["հաց", "hats"], az: "çörək", eu: "ogi", be: ["хлеб", "hleb"],
        bs: "hljeb", bg: ["хляб", "hliab"], ca: "pa", hr: "kruh", cs: ["chléb", "hleb"],
        da: "brød", nl: "brood", en: "bread", et: "leib", fo: "breyð", fi: "leipä",
        fr: "pain", gl: "pan", ka: ["პური", "puri"], de: "Brot", el: ["ψωμί", "psomi"],
        hu: "kenyér", is: "brauð", ga: "arán", it: "pane", lv: "maize", lt: "duona",
        lb: "Brout", mk: ["леб", "leb"], mt: "ħobż", no: "brød", pl: ["chleb", "hleb"],
        pt: "pão", ro: "pâine", ru: ["хлеб", "hleb"], sr: ["хлеб", "hleb"],
        sk: ["chlieb", "hlieb"], sl: "kruh", es: "pan", sv: "bröd", tr: "ekmek",
        uk: ["хліб", "hlib"], cy: "bara",
      },
    },
    church: {
      ref: "ru",
      note: "Western Slavs say kościół, kostel: from Latin castellum, a fort. Eastern and Southern Slavs say церковь, crkva: the same Germanic word as Kirche and church. Latin countries use the Greek ekklesia (église, iglesia, chiesa), but Romanian biserică is basilica.",
      words: {
        sq: "kishë", hy: ["եկեղեցի", "yekeghetsi"], az: "kilsə", eu: "eliza",
        be: ["царква", "tsarkva"], bs: ["crkva", "tsrkva"], bg: ["църква", "tsarkva"], ca: "església",
        hr: ["crkva", "tsrkva"], cs: "kostel", da: "kirke", nl: "kerk", en: "church", et: "kirik",
        fo: "kirkja", fi: "kirkko", fr: "église", gl: "igrexa", ka: ["ეკლესია", "eklesia"],
        de: "Kirche", el: ["εκκλησία", "eklisia"], hu: "templom", is: "kirkja",
        ga: "eaglais", it: ["chiesa", "kiesa"], lv: "baznīca", lt: "bažnyčia",
        lb: "Kierch", mk: ["црква", "tsrkva"], mt: "knisja", no: "kirke", pl: "kościół",
        pt: "igreja", ro: "biserică", ru: ["церковь", "tserkov"], sr: ["црква", "tsrkva"],
        sk: "kostol", sl: ["cerkev", "tserkev"], es: "iglesia", sv: "kyrka", tr: "kilise",
        uk: ["церква", "tserkva"], cy: "eglwys",
      },
    },
    orange: {
      ref: "el",
      note: "The Balkans, Greece, Turkey and Georgia name it after Portugal (πορτοκάλι, portakal, portocală, ფორთოხალი). The North and Russia call it the 'Chinese apple' (apelsin, апельсин, sinaasappel). Poles, Czechs and Slovaks took Italian pomo d'arancia: pomarańcza, pomeranč.",
      words: {
        sq: "portokall", hy: ["նարինջ", "narinj"], az: "portağal", eu: "laranja",
        be: ["апельсін", "apelsin"], bs: "narandža", bg: ["портокал", "portokal"],
        ca: "taronja", hr: "naranča", cs: "pomeranč", da: "appelsin", nl: "sinaasappel",
        en: "orange", et: "apelsin", fo: "appelsin", fi: "appelsiini", fr: "orange",
        gl: "laranxa", ka: ["ფორთოხალი", "portokhali"], de: "Orange",
        el: ["πορτοκάλι", "portokali"], hu: ["narancs", "naranch"], is: "appelsína", ga: "oráiste",
        it: ["arancia", "arancha"], lv: "apelsīns", lt: "apelsinas", lb: "Orange",
        mk: ["портокал", "portokal"], mt: "larinġa", no: "appelsin", pl: "pomarańcza",
        pt: "laranja", ro: "portocală", ru: ["апельсин", "apelsin"],
        sr: ["поморанџа", "pomorandža"], sk: "pomaranč", sl: "pomaranča", es: "naranja",
        sv: "apelsin", tr: "portakal", uk: ["апельсин", "apelsin"], cy: "oren",
      },
    },
    tomato: {
      ref: "hu",
      note: "Italian pomodoro, 'golden apple', became Polish, Russian and Georgian pomidor. Austrian Paradeiser, 'paradise apple', became Hungarian paradicsom, Serbian парадајз and Czech rajče. Most others took the Aztec tomatl: tomate, tomato, domates.",
      words: {
        sq: "domate", hy: ["լոլիկ", "lolik"], az: "pomidor", eu: "tomate",
        be: ["памідор", "pamidor"], bs: "paradajz", bg: ["домат", "domat"], ca: "tomàquet",
        hr: "rajčica", cs: "rajče", da: "tomat", nl: "tomaat", en: "tomato", et: "tomat",
        fo: "tomatur", fi: "tomaatti", fr: "tomate", gl: "tomate", ka: ["პომიდორი", "pomidori"],
        de: "Tomate", el: ["ντομάτα", "domata"], hu: ["paradicsom", "paradichom"], is: "tómatur",
        ga: "tráta", it: "pomodoro", lv: "tomāts", lt: "pomidoras", lb: "Tomat",
        mk: ["домат", "domat"], mt: "tadam", no: "tomat", pl: "pomidor", pt: "tomate",
        ro: "roșie", ru: ["помидор", "pomidor"], sr: ["парадајз", "paradajz"],
        sk: "paradajka", sl: "paradižnik", es: "tomate", sv: "tomat", tr: "domates",
        uk: ["помідор", "pomidor"], cy: "tomato",
      },
    },
    potato: {
      ref: "de",
      note: "Europe named it five ways: 'earth apple' (pomme de terre, aardappel), 'earth thing' (ziemniak, zemiak), 'ground pear' (German dialect Grundbirne: krumpir, Gromper), 'truffle' (Italian tartufolo: Kartoffel, картофель) and 'bulb' (бульба, bulvė). Czech brambor is Brandenburg, where it came from. Spanish patata comes from the Caribbean batata.",
      words: {
        sq: "patate", hy: ["կարտոֆիլ", "kartofil"], az: "kartof", eu: "patata",
        be: ["бульба", "bulba"], bs: "krompir", bg: ["картоф", "kartof"], ca: "patata",
        hr: "krumpir", cs: "brambor", da: "kartoffel", nl: "aardappel", en: "potato",
        et: "kartul", fo: "epli", fi: "peruna", fr: "pomme de terre", gl: "pataca",
        ka: ["კარტოფილი", "kartopili"], de: "Kartoffel", el: ["πατάτα", "patata"],
        hu: "burgonya", is: "kartafla", ga: "práta", it: "patata", lv: "kartupelis",
        lt: "bulvė", lb: "Gromper", mk: ["компир", "kompir"], mt: "patata", no: "potet",
        pl: "ziemniak", pt: "batata", ro: "cartof", ru: ["картофель", "kartofel"],
        sr: ["кромпир", "krompir"], sk: "zemiak", sl: "krompir", es: "patata",
        sv: "potatis", tr: "patates", uk: ["картопля", "kartoplia"], cy: "taten",
      },
    },
    turkey: {
      ref: "nl",
      note: "Everyone named the bird after somewhere else. English says Turkey; Turks, French, Poles and Russians say India (hindi, dinde, indyk, индейка); Portuguese say Peru; Dutch and Scandinavians say Calicut in India (kalkoen, kalkun); Macedonians say Egypt (мисирка).",
      words: {
        sq: "gjel deti", hy: ["հնդկահավ", "hndkahav"], az: "hind toyuğu", eu: "indioilar",
        be: ["індык", "indyk"], bs: "ćurka", bg: ["пуйка", "puika"], ca: "gall dindi",
        hr: "puran", cs: "krocan", da: "kalkun", nl: "kalkoen", en: "turkey", et: "kalkun",
        fo: "kalkun", fi: "kalkkuna", fr: "dinde", gl: "pavo", ka: ["ინდაური", "indauri"],
        de: "Truthahn", el: ["γαλοπούλα", "galopula"], hu: "pulyka", is: "kalkúnn",
        ga: "turcaí", it: "tacchino", lv: "tītars", lt: "kalakutas", lb: "Kalkoun",
        mk: ["мисирка", "misirka"], mt: "dundjan", no: "kalkun", pl: "indyk", pt: "peru",
        ro: "curcan", ru: ["индейка", "indeika"], sr: ["ћурка", "ćurka"], sk: "moriak",
        sl: "puran", es: "pavo", sv: "kalkon", tr: "hindi", uk: ["індик", "indyk"],
        cy: "twrci",
      },
    },
    night: {
      ref: "de",
      note: "One word across all three families: night, Nacht, nuit, notte, noche, noc, ночь, all from the same Indo-European root. Only Finnish, Estonian, Hungarian, Basque and Turkish stand apart.",
      words: {
        sq: "natë", hy: ["գիշեր", "gisher"], az: "gecə", eu: "gau", be: ["ноч", "noch"],
        bs: "noć", bg: ["нощ", "nosht"], ca: "nit", hr: "noć", cs: "noc", da: "nat",
        nl: "nacht", en: "night", et: "öö", fo: "nátt", fi: "yö", fr: "nuit", gl: "noite",
        ka: ["ღამე", "ghame"], de: "Nacht", el: ["νύχτα", "nichta"], hu: "éjszaka",
        is: "nótt", ga: "oíche", it: "notte", lv: "nakts", lt: "naktis", lb: "Nuecht",
        mk: ["ноќ", "nokj"], mt: "lejl", no: "natt", pl: "noc", pt: "noite", ro: "noapte",
        ru: ["ночь", "noch"], sr: ["ноћ", "noć"], sk: "noc", sl: "noč", es: "noche",
        sv: "natt", tr: "gece", uk: ["ніч", "nich"], cy: "nos",
      },
    },
    mother: {
      ref: "en",
      note: "mother, Mutter, madre, matka, мать, máthair: Indo-European again. The outsiders are Finnish äiti, Estonian ema, Hungarian anya, Basque ama and Turkish anne. And in Georgian, mama means father; mother is deda.",
      words: {
        sq: "nënë", hy: ["մայր", "mayr"], az: "ana", eu: "ama", be: ["маці", "matsi"],
        bs: "majka", bg: ["майка", "maika"], ca: "mare", hr: "majka", cs: "matka",
        da: "mor", nl: "moeder", en: "mother", et: "ema", fo: "móðir", fi: "äiti",
        fr: "mère", gl: "nai", ka: ["დედა", "deda"], de: "Mutter", el: ["μητέρα", "mitera"],
        hu: "anya", is: "móðir", ga: "máthair", it: "madre", lv: "māte", lt: "motina",
        lb: "Mamm", mk: ["мајка", "majka"], mt: "omm", no: "mor", pl: "matka", pt: "mãe",
        ro: "mamă", ru: ["мать", "mat"], sr: ["мајка", "majka"], sk: "matka", sl: "mati",
        es: "madre", sv: "mor", tr: "anne", uk: ["мати", "mati"], cy: "mam",
      },
    },
  };

  const presets = root.EuropePresets || require("./presets.js");
  presets.addGroup("stories", STORIES);
})(typeof window !== "undefined" ? window : globalThis);
