// Regenerates map-data.js: the map pre-projected to SVG path strings, so the
// page needs no mapping library and no network to draw Europe.
//
//   npm install && npm run build-map
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoAzimuthalEqualArea, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const { COUNTRIES, REGIONS } = require("../languages.js");

const W = 1000;
const H = 820;
const atlas = JSON.parse(
  readFileSync(require.resolve("world-atlas/countries-50m.json"), "utf8"),
);
const world = feature(atlas, atlas.objects.countries).features;

// The frame Europe is fitted into; everything outside it is clipped away.
const frame = {
  type: "MultiPoint",
  coordinates: [[-24, 36], [48, 36], [-24, 70], [48, 70], [12, 71.5], [12, 34]],
};
const projection = geoAzimuthalEqualArea()
  .rotate([-12, -52])
  .fitExtent([[10, 10], [W - 10, H - 10]], frame)
  .clipExtent([[0, 0], [W, H]]);
const path = geoPath(projection).digits(1);
const xy = (lonLat) => projection(lonLat).map((v) => Math.round(v * 10) / 10);

const byName = new Map(world.map((f) => [f.properties.name, f]));
const countries = {};
for (const c of COUNTRIES) {
  const f = byName.get(c.name);
  if (!f) throw new Error(`no shape for ${c.name} in world-atlas`);
  countries[c.name] = { d: path(f), label: xy(c.label) };
}
const wanted = new Set(COUNTRIES.map((c) => c.name));
const background = world
  .filter((f) => !wanted.has(f.properties.name))
  .map((f) => path(f))
  .filter(Boolean);
const regions = REGIONS.map((r) => ({ name: r.name, lang: r.lang, at: xy(r.at) }));

const data = { width: W, height: H, countries, background, regions };
const out = new URL("../map-data.js", import.meta.url);
writeFileSync(
  out,
  "// Generated by scripts/build-map.mjs from world-atlas (Natural Earth, public domain). Do not edit.\n" +
    `window.EuropeMap = ${JSON.stringify(data)};\n`,
);
console.log(`wrote ${out.pathname}: ${Object.keys(countries).length} countries, ${background.length} background shapes`);
